name: CI for PRs

on:
  pull_request:
    branches:
      - 'master'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build-and-test-linux:
    name: 'Build and Test on Linux'
    runs-on: 'ubuntu-latest'
        
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v4
      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: 'Restore dependencies'
        run: dotnet restore
      - name: 'Build'
        run: dotnet build --no-restore -c Release --property WarningLevel=0 -v q /clp:ErrorsOnly -o ./Build
      - name: 'Run Tests'
        run: dotnet test ./WebApiCarProject.sln --verbosity normal
      - name: Super-Linter
        uses: super-linter/super-linter@v5.7.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.13
      - name: Conventional Commit In Pull Requests
        uses: ytanikin/PRConventionalCommits@1.1.0
      - name: Linting and Formatting Code
        run: dotnet format

  conventional-commits:
      needs: build-and-test-linux
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Conventional Commits Checker
          uses: talos/conventional-pr-action@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: conventional-commits
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Deploy
      run: echo "Miejsce na komendy do deployowania aplikacji"

  update-readme-with-badge:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v2
      - name: Update README with Build Badge
        run: |
          echo '![Build Status](https://github.com/<username>/<repository>/actions/workflows/dotnet-ci.yml/badge.svg?branch=main)' >> README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update README with CI Badge"
          git push
